import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = { title: "Datenschutz", description: "Datenschutzerklärung von Kind People Only.", robots: { index: false, follow: false }, alternates: { canonical: "/datenschutz" } };

const sections = [
  ["1. Verantwortlicher", <>Verantwortlicher im Sinne der Datenschutz-Grundverordnung (DSGVO) ist Aaron Martin, Kanalweg 44, 76133 Karlsruhe. E-Mail: <a href="mailto:info@foreverstudios.xyz" className="text-ink underline underline-offset-2">info@foreverstudios.xyz</a>.</>],
  ["2. Allgemeines zur Datenverarbeitung", <>Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung einer funktionsfähigen Website, zur Abwicklung von Ticketkäufen und zur Erfüllung gesetzlicher Pflichten erforderlich ist oder Sie eingewilligt haben. Rechtsgrundlagen können insbesondere Art. 6 Abs. 1 lit. b, c, f und a DSGVO sein.</>],
  ["3. Hosting und Infrastruktur", <>Die Website und zugehörige Dienste werden über technische Infrastruktur bereitgestellt. Dabei können Zugriffsdaten verarbeitet werden, die der sichere und stabile Betrieb erfordert, z. B. IP-Adresse, Zeitpunkt des Abrufs und technische Fehlerprotokolle.</>],
  ["4. Nutzung der Website", <>Beim Aufruf der Website werden technisch notwendige Informationen verarbeitet, um Inhalte auszuliefern und Missbrauch zu erkennen. Die Speicherung in Logfiles erfolgt vorübergehend, soweit keine längere Aufbewahrung aus Sicherheitsgründen erforderlich ist.</>],
  ["5. Kontaktaufnahme", <>Wenn du uns per E-Mail oder über die <Link href="/kontakt" className="text-ink underline underline-offset-2">Kontaktseite</Link> erreichst, verarbeiten wir die mitgeteilten Daten zur Bearbeitung der Anfrage. Die Daten werden gelöscht, sobald die Speicherung nicht mehr erforderlich ist, sofern keine gesetzlichen Aufbewahrungsfristen entgegenstehen.</>],
  ["6. Nutzerkonto und Authentifizierung", <>Für Funktionen wie die Verwaltung von Tickets oder Profildaten kann ein Nutzerkonto angeboten werden. Die technische Bereitstellung erfolgt über Supabase. Weitere Informationen findest du in der <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" className="text-ink underline underline-offset-2">Datenschutzerklärung von Supabase</a>.</>],
  ["7. Ticketkauf und Zahlungsabwicklung", <>Für den Erwerb von Tickets verarbeiten wir die zur Vertragsabwicklung erforderlichen Daten. Die Zahlungsabwicklung erfolgt über Stripe. Es gelten zusätzlich die <a href="https://stripe.com/de/privacy" target="_blank" rel="noopener noreferrer" className="text-ink underline underline-offset-2">Datenschutzbestimmungen von Stripe</a>.</>],
  ["8. Karten und eingebettete Inhalte", <>Soweit Karten von Drittanbietern eingebunden sind, können beim Aufruf dieser Bereiche Daten an den jeweiligen Anbieter übermittelt werden. Es gelten die Datenschutzhinweise des jeweiligen Anbieters.</>],
  ["9. Cookies und lokale Speicherung", <>Es können technisch notwendige Cookies oder vergleichbare Technologien für die Funktion der Website oder der Anmeldung verwendet werden. Nicht notwendige Cookies setzen wir nur mit der erforderlichen Einwilligung ein.</>],
  ["10. Weitergabe von Daten", <>Eine Übermittlung an Dritte erfolgt nur, wenn dies zur Vertragserfüllung erforderlich ist, wir gesetzlich dazu verpflichtet oder berechtigt sind, oder du eingewilligt hast.</>],
  ["11. Speicherdauer", <>Personenbezogene Daten werden gelöscht oder gesperrt, sobald der Zweck der Speicherung entfällt, sofern dem keine gesetzlichen Aufbewahrungsfristen entgegenstehen.</>],
  ["12. Deine Rechte", <>Du hast unter den gesetzlichen Voraussetzungen Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit sowie Widerspruch. Zur Ausübung genügt eine Nachricht an die oben genannte E-Mail-Adresse.</>],
  ["13. Beschwerde bei einer Aufsichtsbehörde", <>Du hast das Recht, dich bei einer Datenschutzaufsichtsbehörde zu beschweren, insbesondere beim Landesbeauftragten für den Datenschutz Baden-Württemberg.</>],
  ["14. Pflicht zur Bereitstellung", <>Soweit für einen Ticketkauf oder ein Nutzerkonto bestimmte Angaben erforderlich sind, ist die Bereitstellung für den Vertragsschluss bzw. die Nutzung der Funktion notwendig.</>],
  ["15. Automatisierte Entscheidungen", <>Eine ausschließlich auf automatisierter Verarbeitung beruhende Entscheidung einschließlich Profiling im Sinne von Art. 22 DSGVO findet nicht statt.</>],
  ["16. Änderung dieser Erklärung", <>Wir behalten uns vor, diese Datenschutzerklärung anzupassen, damit sie stets den aktuellen rechtlichen Anforderungen entspricht. Es gilt jeweils die zum Zeitpunkt des Besuchs abrufbare Fassung.</>],
] as const;

export default function DatenschutzPage() {
  return (<><Header homeHref="/" /><main className="legal mx-auto max-w-[44rem] px-[clamp(1.25rem,4vw,3rem)] pt-[calc(var(--header-h)+clamp(2.5rem,6vw,4rem))] pb-[clamp(3rem,6vw,5rem)]"><h1 className="mb-8 font-display text-[clamp(2.5rem,7vw,4rem)] font-black leading-none uppercase">Datenschutzerklärung</h1><p className="mb-10 text-sm text-muted">Informationen zur Verarbeitung personenbezogener Daten auf forever.studios.</p><div className="space-y-10 text-sm leading-relaxed text-muted">{sections.map(([title, content]) => <section key={title}><h2 className="mb-3 text-base font-semibold text-ink">{title}</h2><p>{content}</p></section>)}<p className="text-xs text-muted">Stand: März 2026. Weitere Hinweise: <Link href="/impressum" className="text-ink underline underline-offset-2">Impressum</Link> · <Link href="/kontakt" className="text-ink underline underline-offset-2">Kontakt</Link>.</p></div></main><Footer /></>);
}
